label_dir: 'labels'
image_dir: 'images'

auto_save: true
display_label_popup: true
store_data: false
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

flags: ["hard_im"]
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

default_shape_color: [0, 255, 0]
shape_color: manual  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: null

label_colors:
  entrance: [255,0,0]
  endpoint: [0,255,0]
  second_entrance: [0,0,255]
  stoppoint: [255,255,0]
  intermediate: [0,255,255]
  inv_entrance: [0,0,0]
  inv_endpoint: [0,0,0]
  inv_second_entrance: [0,0,0]
  inv_stoppoint: [0,0,0]
  inv_intermediate: [0,0,0]


mouse:
  left_mouse: 'entrance'
  right_mouse: 'endpoint'
  middle_mouse: 'second_entrance'
  shift_left_mouse: 'stoppoint'
  alt_left_mouse: 'intermediate'
  ctrl_left_mouse: 'inv_entrance'
  ctrl_right_mouse: 'inv_endpoint'
  ctrl_middle_mouse: 'inv_second_entrance'
  shift_right_mouse: 'inv_stoppoint'
  alt_right_mouse: 'inv_intermediate'
  

shape:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 0]  # transparent
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]
  point_size: 8
  ratio: 0.5 #0.0864

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10
  # show crosshair
  crosshair:
    polygon: false
    rectangle: true
    circle: false
    line: false
    point: false
    linestrip: false

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: null
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: Ctrl+N
  create_linestrip: null
  edit_polygon: E
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  copy_polygon: Ctrl+C
  paste_polygon: Ctrl+V
  undo: Ctrl+Z
  undo_last_point: Ctrl+U
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+P
  remove_selected_point: [Meta+H, Backspace]
  show_text: space
